### PR TITLE
naming branches

### PR DESCRIPTION
**Pull request by swavkulinski**
how we name branches

### CODE REVIEW

**Comment by fada21** [comment]
Why do we need names? Commits have their authors. And to stick to gitflow it should be something like hotfix-SG-1012-image-in-article-is-cut-off

**Comment by swavkulinski** [comment]
because sometimes author of the commit is different then the owner of the story. Also it is easy to see your branches by simply 

git branch --list

**Comment by shaps80** [comment]
On iOS we do something similar. e.g. feature/shaps-feature_name
Some people just initial e.g. feature/is-feature_name
Then I know its Iain Smith ;)

**Comment by ghost** [comment]
got to say, I'm not a big fan of this...but its your call. If you're pairing for example...who's the owner? Even if you're not, surely the owner is clear from commit history and pull requests as Lukasz says. In terms of being able to see which branch is yours, I don't see that as a big problem if we regularly delete obsolete branches and keep the lifetime of branches short (by breaking changes down into small steps)

**Comment by vampdesigns** [comment]
I agree with Swav. You can obviously get all this info from commits but it does help with organisation and clarity when using sourcetree for example. Its pretty clear which branches you own and are the main ones you would be working on

**Comment by stevewrw** [comment]
I also agree with the view of having author names within the branch name.

Its true that you can get the author easily enough from the commit, however
being within the branch name feels a bit more 'in plain view'.

On 2 March 2015 at 10:47, vampdesigns notifications@github.com wrote:

> I agree with Swav. You can obviously get all this info from commits but it
> does help with organisation and clarity when using sourcetree for example.
> Its pretty clear which branches you own and are the main ones you would be
> working on
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/theappbusiness/Android-Code-Guidelines/pull/1#issuecomment-76691208
> .

## 

_Stephen Wilson_
Head Of Engineering

The App Business
20-24 Broadwick Street
London W1F 8HT
+44 203 657 9785
www.theappbusiness.com

BIMA Awards: On Track wins User Experience category
http://www.bimaawards.com/2014-winners.php
Drum Digital Census: voted no.1 for client satisfaction
http://www.thedrum.com/news/2014/09/17/sapientnitro-heathwallace-great-fridays-bell-pottinger-wired-head-financial-polls
Sunday Times Tech Track 100: ranked in UK top 30 for fastest growth
http://www.fasttrack.co.uk/fasttrack/leagues/tech100leaguetable.asp?siteID=3&searchName=&yr=2014&sort=num&area1=99

Check out our latest thinking in our journal
http://www.theappbusiness.com/journal/ and follow us on:
Twitter http://twitter.com/theappbusiness • LinkedIn
http://www.linkedin.com/company/the-app-business • Google+
http://www.google.com/+TheappbusinessTAB • Dribbble
http://dribbble.com/theappbusiness • Instagram
http://instagram.com/theappbusiness • Facebook
http://www.facebook.com/theappbusiness

The App Business Limited is a company registered in England and Wales
Registered number: 01897720
Office location: 20-24 Broadwick Street, London, United Kingdom, W1F 8HT
Registered address: Clapton Revel, Falcons Croft, Wooburn Moor, High
Wycombe, Buckinghamshire HP10 0NP

**Comment by ghost** [comment]
i'm happy as long as we don't use this because:
i) we're having long-lived branches rather than breaking down changes properly
ii) we're not pairing or collaborating very effectively so we're finding it harder to know what other people are doing
iii). we have too much work in progress so its hard to filter out all the living branches we have

If the reason we need to track author names so closely is because any of the above are true, then we're solving the wrong problem. If its for other reasons then fair enough, whatever works for your workflow. I don't see us adopting this convention across the board though...I don't see this as solving any particular problem on other teams.

**Pull request closed without merging**
